apiVersion: apps/v1
kind: Deployment
metadata:
  name: mondodb
spec:
  selector:
    matchLabels:
      app: mondodb
  template:
    metadata:
      labels:
        app: mondodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.2.8
          ports:
          - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongouser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopwd