apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: firstreplicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-color
template:
  metadata:
    labels:
      app: nginx-color
  spec:
    containers:
      - name: nginx-color
        image: kubdevio/nginx-color:blue